sudo: false

language: python

python:
- '3.6'
- nightly

matrix:
  # Ignore failures for unstable versions
  allow_failures:
    - python: nightly

install:
  - python -m pip install -r requirements.txt
  - python -m pip install -e .

before_script:
  - python -m flake8

script:
  - python -m pytest -v

deploy:
  provider: pypi
  user: cmccandless
  password: $PYPI_PASSWORD
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: cmccandless/pyarnold
    python: '3.6'
